/** T1 — VFR into IMC / spatial disorientation (A1). Fictional only. */

import type { FailureModeTemplate } from './schema';

/**
 * Typical chain (B2.4): get-there-itis + weak IFR currency → entered cloud
 * at night → graveyard spiral → CFIT or in-flight breakup.
 */
export const T1_VFR_IMC: FailureModeTemplate = {
  id: 'T1',
  name: 'VFR into IMC / spatial disorientation',
  summary:
    'Night VFR continued into IMC; spatial disorientation and loss of control.',
  archetypes: ['A1'],
  parameters: [
    {
      key: 'timeOfDay',
      description: 'Accident local time-of-day band',
      defaultValue: 'night',
    },
    {
      key: 'outcomeMode',
      description: 'cfit | in_flight_breakup',
      defaultValue: 'cfit',
    },
    {
      key: 'ceilingFt',
      description: 'Broken/overcast ceiling near route (ft AGL)',
      defaultValue: 1200,
    },
  ],
  nodes: [
    {
      id: 'latent.schedule_pressure',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'The pilot elected to complete the trip despite a known weather deterioration in order to meet a personal schedule.',
      revealedBy: [
        { evidenceId: 'hp.72hour_history', strength: 0.75 },
        { evidenceId: 'ops.family_interview_schedule', strength: 0.7 },
        { evidenceId: 'ops.flight_plan_briefing', strength: 0.55 },
      ],
    },
    {
      id: 'precondition.ifr_currency_lapsed',
      kind: 'precondition',
      tier: 'precondition',
      text: "The pilot's instrument currency had lapsed and recent instrument practice was limited.",
      revealedBy: [
        { evidenceId: 'ops.pilot_certificates_recency', strength: 0.95 },
        { evidenceId: 'ops.training_records', strength: 0.85 },
      ],
    },
    {
      id: 'initiating.continued_vfr_imc',
      kind: 'initiatingEvent',
      tier: 'probableCause',
      text: 'The pilot continued visual flight rules flight into instrument meteorological conditions at night.',
      revealedBy: [
        { evidenceId: 'wx.metar_taf_package', strength: 0.9 },
        { evidenceId: 'adsb.track', strength: 0.8 },
        { evidenceId: 'nvm.portable_gps', strength: 0.75 },
        { evidenceId: 'cvr.transcript', strength: 0.7 },
      ],
    },
    {
      id: 'propagation.spatial_disorientation',
      kind: 'propagation',
      tier: 'contributing',
      text: 'After entering clouds the pilot experienced spatial disorientation and lost aircraft control in a developing spiral dive.',
      revealedBy: [
        { evidenceId: 'adsb.track', strength: 0.85 },
        { evidenceId: 'structures.wreckage_map', strength: 0.7 },
        { evidenceId: 'fdr.readout', strength: 0.9 },
        { evidenceId: 'witness.ground_observers', strength: 0.55 },
      ],
    },
    {
      id: 'outcome.terrain_impact',
      kind: 'outcome',
      tier: 'contributing',
      text: 'The airplane impacted rising terrain in a steep descending right turn.',
      revealedBy: [
        { evidenceId: 'structures.wreckage_map', strength: 0.95 },
        { evidenceId: 'structures.ground_scar_survey', strength: 0.9 },
        { evidenceId: 'adsb.track', strength: 0.65 },
      ],
    },
  ],
  edges: [
    { from: 'latent.schedule_pressure', to: 'initiating.continued_vfr_imc' },
    { from: 'precondition.ifr_currency_lapsed', to: 'initiating.continued_vfr_imc' },
    { from: 'initiating.continued_vfr_imc', to: 'propagation.spatial_disorientation' },
    { from: 'propagation.spatial_disorientation', to: 'outcome.terrain_impact' },
  ],
  flightScriptHooks: [
    {
      phase: 'preflight',
      eventId: 'event.wx_brief_marginal',
      description: 'Pilot receives marginal VFR briefing; elects to depart.',
      atSeconds: 0,
    },
    {
      phase: 'cruise',
      eventId: 'event.enter_imc',
      description: 'Aircraft enters cloud layer; external visual references lost.',
      atSeconds: 180,
    },
    {
      phase: 'cruise',
      eventId: 'event.graveyard_spiral',
      description: 'Bank and airspeed increase in unrecognized spiral dive.',
      atSeconds: 240,
    },
    {
      phase: 'descent',
      eventId: 'event.terrain_impact',
      description: 'Ground proximity ends the flight; CFIT geometry.',
      atSeconds: 30,
    },
  ],
  evidenceHooks: [
    {
      evidenceId: 'wx.metar_taf_package',
      group: 'meteorology',
      title: 'METAR/TAF/AIRMET package along route',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'ops.pilot_certificates_recency',
      group: 'operations',
      title: 'Pilot certificates and instrument currency',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'ops.training_records',
      group: 'operations',
      title: 'Recent training and proficiency records',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'ops.flight_plan_briefing',
      group: 'operations',
      title: 'Filed flight plan and weather briefing record',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'ops.family_interview_schedule',
      group: 'operations',
      title: 'Family / passenger-purpose interview (schedule pressure)',
      withoutRecorders: true,
      renderer: 'transcript',
      costStub: 2,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'hp.72hour_history',
      group: 'humanPerformance',
      title: '72-hour history worksheet',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'adsb.track',
      group: 'atc',
      title: 'ADS-B track reconstruction',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'nvm.portable_gps',
      group: 'systems',
      title: 'Portable / panel GPS track log',
      withoutRecorders: true,
      renderer: 'trace',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'witness.ground_observers',
      group: 'witnesses',
      title: 'Ground observer statements',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'structures.wreckage_map',
      group: 'structures',
      title: 'Wreckage distribution map and PIP',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'structures.ground_scar_survey',
      group: 'structures',
      title: 'Ground-scar and impact-angle survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'cvr.transcript',
      group: 'recorders',
      title: 'CVR transcript (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'transcript',
      costStub: 3,
      leadTimeStub: 14,
    },
    {
      evidenceId: 'fdr.readout',
      group: 'recorders',
      title: 'Lightweight FDR readout (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'trace',
      costStub: 3,
      leadTimeStub: 14,
    },
  ],
  redHerringPool: [
    {
      id: 'nonCausal.minor_logbook_gap',
      text: 'A minor airframe logbook entry gap existed for an unrelated inspection item; it did not contribute to the accident.',
      poolTag: 'maintenance',
    },
    {
      id: 'nonCausal.recent_ownership_change',
      text: 'The airplane had changed owners three months earlier; ownership transfer paperwork was complete and unrelated to the flight.',
      poolTag: 'records',
    },
    {
      id: 'nonCausal.atc_phraseology_slip',
      text: 'A controller used nonstandard phraseology on an earlier frequency; the crew read back correctly and the slip was not causal.',
      poolTag: 'atc',
    },
    {
      id: 'nonCausal.deferred_nav_light',
      text: 'A deferred navigation-light MEL item was open; lighting was not a factor in the night IMC encounter.',
      poolTag: 'mel',
    },
  ],
  redHerringDraw: { min: 1, max: 3 },
  parCostStub: {
    investigatorDays: 14,
    calendarDays: 40,
    evidenceSet: [
      'wx.metar_taf_package',
      'ops.pilot_certificates_recency',
      'adsb.track',
      'structures.wreckage_map',
      'hp.72hour_history',
    ],
  },
};
