/** T2 — Fuel exhaustion / starvation (A1, A2). Fictional only. */

import type { FailureModeTemplate } from './schema';

/**
 * Typical chain (B2.4): planning error or gauge defect or selector mis-set
 * → engine power loss → forced landing / stall.
 */
export const T2_FUEL_EXHAUSTION: FailureModeTemplate = {
  id: 'T2',
  name: 'Fuel exhaustion / starvation',
  summary:
    'Fuel planning or management error leads to power loss and forced landing or stall.',
  archetypes: ['A1', 'A2'],
  parameters: [
    {
      key: 'mode',
      description: 'exhaustion | starvation_selector | gauge_defect',
      defaultValue: 'exhaustion',
    },
    {
      key: 'phaseOfLoss',
      description: 'Flight phase when power is lost',
      defaultValue: 'approach',
    },
    {
      key: 'usableFuelAtStartGal',
      description: 'Usable fuel onboard at departure (gal)',
      defaultValue: 28,
    },
  ],
  nodes: [
    {
      id: 'latent.fuel_planning_error',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'The pilot planned the flight with inadequate usable fuel reserves for the intended route and expected conditions.',
      revealedBy: [
        { evidenceId: 'ops.flight_plan_fuel', strength: 0.9 },
        { evidenceId: 'ops.weight_balance_fuel', strength: 0.75 },
        { evidenceId: 'ops.pilot_interview_fuel', strength: 0.65 },
      ],
    },
    {
      id: 'precondition.fuel_quantity_misread',
      kind: 'precondition',
      tier: 'precondition',
      text: 'Preflight fuel quantity determination did not correctly establish usable fuel remaining in the selected tanks.',
      revealedBy: [
        { evidenceId: 'ops.preflight_checklist_fuel', strength: 0.7 },
        { evidenceId: 'powerplants.fuel_system_exam', strength: 0.85 },
        { evidenceId: 'nvm.engine_monitor', strength: 0.6 },
      ],
    },
    {
      id: 'initiating.fuel_exhaustion',
      kind: 'initiatingEvent',
      tier: 'probableCause',
      text: 'The engine lost power due to fuel exhaustion (or starvation from an improper tank selection).',
      revealedBy: [
        { evidenceId: 'powerplants.fuel_system_exam', strength: 0.95 },
        { evidenceId: 'powerplants.engine_field_exam', strength: 0.8 },
        { evidenceId: 'nvm.engine_monitor', strength: 0.85 },
        { evidenceId: 'fdr.readout', strength: 0.75 },
      ],
    },
    {
      id: 'propagation.forced_landing_attempt',
      kind: 'propagation',
      tier: 'contributing',
      text: 'After power loss the pilot attempted an off-airport forced landing at low altitude with limited energy margin.',
      revealedBy: [
        { evidenceId: 'adsb.track', strength: 0.8 },
        { evidenceId: 'witness.ground_observers', strength: 0.7 },
        { evidenceId: 'cvr.transcript', strength: 0.75 },
        { evidenceId: 'structures.wreckage_map', strength: 0.65 },
      ],
    },
    {
      id: 'outcome.stall_impact',
      kind: 'outcome',
      tier: 'contributing',
      text: 'The airplane stalled during the forced-landing attempt and impacted terrain.',
      revealedBy: [
        { evidenceId: 'structures.wreckage_map', strength: 0.9 },
        { evidenceId: 'structures.ground_scar_survey', strength: 0.85 },
        { evidenceId: 'adsb.track', strength: 0.7 },
      ],
    },
  ],
  edges: [
    { from: 'latent.fuel_planning_error', to: 'initiating.fuel_exhaustion' },
    { from: 'precondition.fuel_quantity_misread', to: 'initiating.fuel_exhaustion' },
    { from: 'initiating.fuel_exhaustion', to: 'propagation.forced_landing_attempt' },
    { from: 'propagation.forced_landing_attempt', to: 'outcome.stall_impact' },
  ],
  flightScriptHooks: [
    {
      phase: 'preflight',
      eventId: 'event.fuel_plan_optimistic',
      description: 'Pilot accepts optimistic burn and reserve assumptions.',
      atSeconds: 0,
    },
    {
      phase: 'cruise',
      eventId: 'event.fuel_qty_trending_low',
      description: 'Fuel quantity and flow trends toward empty on selected tank.',
      atSeconds: 900,
    },
    {
      phase: 'approach',
      eventId: 'event.power_loss_fuel',
      description: 'Engine power loss from fuel exhaustion/starvation.',
      atSeconds: 60,
    },
    {
      phase: 'landing',
      eventId: 'event.forced_landing_stall',
      description: 'Forced-landing attempt ends in stall and terrain impact.',
      atSeconds: 20,
    },
  ],
  evidenceHooks: [
    {
      evidenceId: 'ops.flight_plan_fuel',
      group: 'operations',
      title: 'Flight plan and fuel planning worksheet',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'ops.weight_balance_fuel',
      group: 'operations',
      title: 'Weight and balance / fuel load record',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'ops.pilot_interview_fuel',
      group: 'operations',
      title: 'Pilot / operator interview (fuel planning)',
      withoutRecorders: true,
      renderer: 'transcript',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'ops.preflight_checklist_fuel',
      group: 'operations',
      title: 'Preflight checklist and fuel-quantity procedure notes',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'powerplants.fuel_system_exam',
      group: 'powerplants',
      title: 'Fuel-system quantity, selector, and filter exam',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 3,
      leadTimeStub: 7,
    },
    {
      evidenceId: 'powerplants.engine_field_exam',
      group: 'powerplants',
      title: 'Engine field exam (power signature / fuel feed)',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'nvm.engine_monitor',
      group: 'systems',
      title: 'Engine-monitor NVM (FF / fuel totalizer)',
      withoutRecorders: true,
      renderer: 'trace',
      costStub: 2,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'adsb.track',
      group: 'atc',
      title: 'ADS-B track reconstruction',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'witness.ground_observers',
      group: 'witnesses',
      title: 'Ground observer statements',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'structures.wreckage_map',
      group: 'structures',
      title: 'Wreckage distribution map and PIP',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'structures.ground_scar_survey',
      group: 'structures',
      title: 'Ground-scar and impact-angle survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'cvr.transcript',
      group: 'recorders',
      title: 'CVR transcript (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'transcript',
      costStub: 3,
      leadTimeStub: 14,
    },
    {
      evidenceId: 'fdr.readout',
      group: 'recorders',
      title: 'Lightweight FDR readout (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'trace',
      costStub: 3,
      leadTimeStub: 14,
    },
  ],
  redHerringPool: [
    {
      id: 'nonCausal.carb_ice_favorable_wx',
      text: 'Weather was favorable for carburettor icing, but the power-loss signature and empty usable fuel ruled carb ice out as causal.',
      poolTag: 'weather',
    },
    {
      id: 'nonCausal.minor_logbook_gap',
      text: 'A minor airframe logbook entry gap existed for an unrelated inspection item; it did not contribute to the accident.',
      poolTag: 'maintenance',
    },
    {
      id: 'nonCausal.checklist_deviation_nonfactor',
      text: 'A checklist item unrelated to fuel was skipped on taxi; it did not contribute to the power loss.',
      poolTag: 'crew',
    },
    {
      id: 'nonCausal.prior_asrs_style',
      text: 'The operator had a prior ASRS-style report of a fuel-gauge flicker on another airplane; that report was unrelated to this airplane.',
      poolTag: 'records',
    },
  ],
  redHerringDraw: { min: 1, max: 3 },
  parCostStub: {
    investigatorDays: 16,
    calendarDays: 45,
    evidenceSet: [
      'ops.flight_plan_fuel',
      'powerplants.fuel_system_exam',
      'nvm.engine_monitor',
      'adsb.track',
      'structures.wreckage_map',
    ],
  },
};
