/** T2 — Fuel exhaustion / starvation (A1, A2). Fictional only. */

import type { FailureModeTemplate } from './schema';

/**
 * Typical chain (B2.4): planning error or gauge defect or selector
 * mis-set → engine power loss → forced landing / stall.
 */
export const T2_FUEL: FailureModeTemplate = {
  id: 'T2',
  name: 'Fuel exhaustion / starvation',
  summary:
    'Fuel planning or management error leads to power loss and forced landing.',
  archetypes: ['A1', 'A2'],
  parameters: [
    {
      key: 'mode',
      description: 'exhaustion | starvation_selector | gauge_defect',
      defaultValue: 'exhaustion',
    },
    {
      key: 'plannedFuelGallons',
      description: 'Fuel quantity the pilot believed was aboard',
      defaultValue: 48,
    },
    {
      key: 'actualFuelGallons',
      description: 'Fuel quantity actually usable at departure',
      defaultValue: 28,
    },
  ],
  nodes: [
    {
      id: 'latent.fuel_planning_error',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'Preflight fuel planning used an optimistic burn rate and did not include adequate reserve for the planned route and alternate.',
      revealedBy: [
        { evidenceId: 'ops.flight_plan_fuel_calc', strength: 0.9 },
        { evidenceId: 'ops.pilot_interview_fuel', strength: 0.7 },
        { evidenceId: 'ops.weight_balance_sheet', strength: 0.6 },
      ],
    },
    {
      id: 'precondition.no_visual_fuel_check',
      kind: 'precondition',
      tier: 'precondition',
      text: 'The pilot did not verify fuel quantity by visual inspection of the tanks before departure.',
      revealedBy: [
        { evidenceId: 'ops.pilot_interview_fuel', strength: 0.8 },
        { evidenceId: 'witness.line_service', strength: 0.65 },
        { evidenceId: 'ops.fueling_records', strength: 0.75 },
      ],
    },
    {
      id: 'initiating.fuel_exhaustion',
      kind: 'initiatingEvent',
      tier: 'probableCause',
      text: 'The engine lost power when usable fuel was exhausted in cruise.',
      revealedBy: [
        { evidenceId: 'powerplants.fuel_system_exam', strength: 0.95 },
        { evidenceId: 'nvm.engine_monitor', strength: 0.85 },
        { evidenceId: 'adsb.track', strength: 0.7 },
        { evidenceId: 'fdr.readout', strength: 0.8 },
      ],
    },
    {
      id: 'propagation.forced_landing_stall',
      kind: 'propagation',
      tier: 'contributing',
      text: 'During the attempted forced landing the airplane stalled at low altitude and descended uncontrolled into terrain.',
      revealedBy: [
        { evidenceId: 'adsb.track', strength: 0.8 },
        { evidenceId: 'structures.wreckage_map', strength: 0.75 },
        { evidenceId: 'witness.ground_observers', strength: 0.6 },
        { evidenceId: 'cvr.transcript', strength: 0.7 },
      ],
    },
    {
      id: 'outcome.off_airport_impact',
      kind: 'outcome',
      tier: 'contributing',
      text: 'The airplane impacted an open field short of a suitable forced-landing site.',
      revealedBy: [
        { evidenceId: 'structures.wreckage_map', strength: 0.95 },
        { evidenceId: 'structures.ground_scar_survey', strength: 0.9 },
        { evidenceId: 'survival.injury_table', strength: 0.5 },
      ],
    },
  ],
  edges: [
    { from: 'latent.fuel_planning_error', to: 'initiating.fuel_exhaustion' },
    { from: 'precondition.no_visual_fuel_check', to: 'initiating.fuel_exhaustion' },
    { from: 'initiating.fuel_exhaustion', to: 'propagation.forced_landing_stall' },
    { from: 'propagation.forced_landing_stall', to: 'outcome.off_airport_impact' },
  ],
  flightScriptHooks: [
    {
      phase: 'preflight',
      eventId: 'event.fuel_assumed_full',
      description: 'Pilot relies on gauge / memory; skips stick/visual check.',
    },
    {
      phase: 'cruise',
      eventId: 'event.fuel_flow_zero',
      description: 'Usable fuel reaches zero; fuel flow collapses; engine quits.',
      atSeconds: 900,
    },
    {
      phase: 'descent',
      eventId: 'event.forced_landing_attempt',
      description: 'Best-glide toward a field; airspeed decays near flare.',
      atSeconds: 60,
    },
    {
      phase: 'landing',
      eventId: 'event.stall_impact',
      description: 'Low-altitude stall; off-airport impact.',
      atSeconds: 10,
    },
  ],
  evidenceHooks: [
    {
      evidenceId: 'ops.flight_plan_fuel_calc',
      group: 'operations',
      title: 'Flight plan and fuel-calculation worksheet',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'ops.weight_balance_sheet',
      group: 'operations',
      title: 'Weight-and-balance / load sheet',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'ops.fueling_records',
      group: 'operations',
      title: 'FBO fueling tickets and tankering history',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'ops.pilot_interview_fuel',
      group: 'operations',
      title: 'Pilot interview — fuel planning and preflight',
      withoutRecorders: true,
      renderer: 'transcript',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'witness.line_service',
      group: 'witnesses',
      title: 'Line-service witness (preflight / fueling)',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'witness.ground_observers',
      group: 'witnesses',
      title: 'Ground observer statements near impact',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'powerplants.fuel_system_exam',
      group: 'powerplants',
      title: 'Fuel-system field exam and tank quantity',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'nvm.engine_monitor',
      group: 'powerplants',
      title: 'Engine-monitor NVM (FF/RPM/EGT)',
      withoutRecorders: true,
      renderer: 'trace',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'adsb.track',
      group: 'atc',
      title: 'ADS-B track reconstruction',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'structures.wreckage_map',
      group: 'structures',
      title: 'Wreckage distribution map and PIP',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'structures.ground_scar_survey',
      group: 'structures',
      title: 'Ground-scar and impact-angle survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'survival.injury_table',
      group: 'survivalFactors',
      title: 'Injury table and restraint state',
      withoutRecorders: true,
      renderer: 'table',
      costStub: 1,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'cvr.transcript',
      group: 'recorders',
      title: 'CVR transcript (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'transcript',
      costStub: 3,
      leadTimeStub: 14,
    },
    {
      evidenceId: 'fdr.readout',
      group: 'recorders',
      title: 'Lightweight FDR readout (A2 when fitted)',
      withoutRecorders: false,
      renderer: 'trace',
      costStub: 3,
      leadTimeStub: 14,
    },
  ],
  redHerringPool: [
    {
      id: 'nonCausal.marginal_legal_weather',
      text: 'Departure weather was marginal but legal VFR; weather was not a factor in the power loss.',
      poolTag: 'weather',
    },
    {
      id: 'nonCausal.checklist_skip_lights',
      text: 'The pilot skipped an exterior-lights checklist item; the omission did not affect fuel state or the forced landing.',
      poolTag: 'checklist',
    },
    {
      id: 'nonCausal.prior_incident_history',
      text: 'The pilot had a prior hard-landing incident five years earlier; it was unrelated to fuel management on this flight.',
      poolTag: 'history',
    },
    {
      id: 'nonCausal.minor_oil_seep',
      text: 'A minor oil seep was noted on the lower cowling; oil quantity was adequate and the seep was not causal.',
      poolTag: 'maintenance',
    },
  ],
  redHerringDraw: { min: 1, max: 3 },
  parCostStub: {
    investigatorDays: 12,
    calendarDays: 35,
    evidenceSet: [
      'ops.flight_plan_fuel_calc',
      'ops.fueling_records',
      'powerplants.fuel_system_exam',
      'nvm.engine_monitor',
      'adsb.track',
      'structures.wreckage_map',
    ],
  },
};
