/** T4 — Airframe icing + deferred anti-ice defect (A2). Fictional only. */

import type { FailureModeTemplate } from './schema';

/**
 * Typical chain (B2.4): MEL misuse + dispatch pressure → boots inop in
 * icing → wing/tailplane stall on approach.
 */
export const T4_ICING: FailureModeTemplate = {
  id: 'T4',
  name: 'Airframe icing + deferred anti-ice defect',
  summary:
    'Improper MEL deferral of de-ice boots; airframe ice; stall on approach.',
  archetypes: ['A2'],
  parameters: [
    {
      key: 'melCategory',
      description: 'MEL category letter for the deferred boot system',
      defaultValue: 'C',
    },
    {
      key: 'icingBandLowFt',
      description: 'Base of forecast icing band (ft)',
      defaultValue: 2000,
    },
    {
      key: 'icingBandHighFt',
      description: 'Top of forecast icing band (ft)',
      defaultValue: 8000,
    },
  ],
  nodes: [
    {
      id: 'latent.mel_misuse',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'Maintenance control improperly deferred an inoperative de-ice boot beyond the MEL category limits and without required repeat inspections.',
      revealedBy: [
        { evidenceId: 'maint.mel_deferred_list', strength: 0.95 },
        { evidenceId: 'maint.work_orders_boots', strength: 0.9 },
        { evidenceId: 'maint.mel_procedures_audit', strength: 0.8 },
      ],
    },
    {
      id: 'latent.dispatch_pressure',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'Dispatch pressure to keep the evening rotation led the operator to release the flight with known anti-ice degradation.',
      revealedBy: [
        { evidenceId: 'ops.dispatch_release', strength: 0.85 },
        { evidenceId: 'ops.dispatcher_interview', strength: 0.75 },
        { evidenceId: 'parties.operator_schedule', strength: 0.6 },
      ],
    },
    {
      id: 'precondition.boots_inoperative',
      kind: 'precondition',
      tier: 'precondition',
      text: 'The pneumatic de-ice boots on the outboard wing were inoperative at dispatch.',
      revealedBy: [
        { evidenceId: 'maint.mel_deferred_list', strength: 0.9 },
        { evidenceId: 'systems.cockpit_switch_exam', strength: 0.7 },
        { evidenceId: 'cvr.transcript', strength: 0.65 },
      ],
    },
    {
      id: 'initiating.airframe_icing',
      kind: 'initiatingEvent',
      tier: 'probableCause',
      text: 'The airplane accumulated unprotected airframe ice while operating in forecast icing conditions with inoperative de-ice boots.',
      revealedBy: [
        { evidenceId: 'wx.icing_airmet_pirep', strength: 0.9 },
        { evidenceId: 'fdr.readout', strength: 0.85 },
        { evidenceId: 'cvr.transcript', strength: 0.8 },
        { evidenceId: 'witness.cabin_ice_observation', strength: 0.55 },
      ],
    },
    {
      id: 'propagation.wing_tail_stall',
      kind: 'propagation',
      tier: 'contributing',
      text: 'Ice-contaminated wing and tailplane aerodynamics produced a stall during configuration change on approach.',
      revealedBy: [
        { evidenceId: 'fdr.readout', strength: 0.95 },
        { evidenceId: 'perf.approach_energy_study', strength: 0.85 },
        { evidenceId: 'cvr.transcript', strength: 0.75 },
        { evidenceId: 'adsb.track', strength: 0.65 },
      ],
    },
    {
      id: 'outcome.approach_impact',
      kind: 'outcome',
      tier: 'contributing',
      text: 'The airplane descended uncontrolled and impacted terrain short of the runway threshold.',
      revealedBy: [
        { evidenceId: 'structures.wreckage_map', strength: 0.95 },
        { evidenceId: 'structures.ground_scar_survey', strength: 0.9 },
        { evidenceId: 'adsb.track', strength: 0.7 },
      ],
    },
  ],
  edges: [
    { from: 'latent.mel_misuse', to: 'precondition.boots_inoperative' },
    { from: 'latent.dispatch_pressure', to: 'precondition.boots_inoperative' },
    { from: 'precondition.boots_inoperative', to: 'initiating.airframe_icing' },
    { from: 'initiating.airframe_icing', to: 'propagation.wing_tail_stall' },
    { from: 'propagation.wing_tail_stall', to: 'outcome.approach_impact' },
  ],
  flightScriptHooks: [
    {
      phase: 'preflight',
      eventId: 'event.mel_release',
      description: 'Flight released with boots MEL open; icing forecast overlooked.',
    },
    {
      phase: 'cruise',
      eventId: 'event.enter_icing',
      description: 'Airplane enters icing band; boots commanded but ineffective.',
      atSeconds: 400,
    },
    {
      phase: 'approach',
      eventId: 'event.config_stall',
      description: 'Flap extension / pitch change triggers ice-contaminated stall.',
      atSeconds: 90,
    },
    {
      phase: 'approach',
      eventId: 'event.short_of_threshold',
      description: 'Uncontrolled descent; impact short of threshold.',
      atSeconds: 120,
    },
  ],
  evidenceHooks: [
    {
      evidenceId: 'maint.mel_deferred_list',
      group: 'maintenanceRecords',
      title: 'MEL / deferred-items list',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'maint.work_orders_boots',
      group: 'maintenanceRecords',
      title: 'Work orders — de-ice boot repairs',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'maint.mel_procedures_audit',
      group: 'maintenanceRecords',
      title: 'MEL procedures and repeat-deferral audit',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'ops.dispatch_release',
      group: 'operations',
      title: 'Dispatch release and weather package',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'ops.dispatcher_interview',
      group: 'operations',
      title: 'Dispatcher interview',
      withoutRecorders: true,
      renderer: 'transcript',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'parties.operator_schedule',
      group: 'parties',
      title: 'Operator schedule / rotation pressure records',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'systems.cockpit_switch_exam',
      group: 'systems',
      title: 'Cockpit anti-ice switch and annunciator exam',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'wx.icing_airmet_pirep',
      group: 'meteorology',
      title: 'AIRMET/SIGMET icing and PIREP package',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 1,
      leadTimeStub: 1,
    },
    {
      evidenceId: 'witness.cabin_ice_observation',
      group: 'witnesses',
      title: 'Cabin occupant ice / buffet observations',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 3,
    },
    {
      evidenceId: 'adsb.track',
      group: 'atc',
      title: 'ADS-B track reconstruction',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'structures.wreckage_map',
      group: 'structures',
      title: 'Wreckage distribution map and PIP',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'structures.ground_scar_survey',
      group: 'structures',
      title: 'Ground-scar and impact-angle survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'perf.approach_energy_study',
      group: 'operations',
      title: 'Approach energy / stall performance study',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 4,
      leadTimeStub: 20,
    },
    {
      evidenceId: 'cvr.transcript',
      group: 'recorders',
      title: 'CVR transcript',
      withoutRecorders: false,
      renderer: 'transcript',
      costStub: 3,
      leadTimeStub: 14,
    },
    {
      evidenceId: 'fdr.readout',
      group: 'recorders',
      title: 'Lightweight FDR readout',
      withoutRecorders: false,
      renderer: 'trace',
      costStub: 3,
      leadTimeStub: 14,
    },
  ],
  redHerringPool: [
    {
      id: 'nonCausal.crew_fatigue_nonfactor',
      text: 'Both crewmembers were near the end of a legal duty day; fatigue was evaluated and determined not to be causal.',
      poolTag: 'fatigue',
    },
    {
      id: 'nonCausal.unrelated_deferred_pack',
      text: 'An unrelated cabin pack MEL item was open; pressurization was normal and the item was not causal.',
      poolTag: 'mel',
    },
    {
      id: 'nonCausal.atc_speed_assignment',
      text: 'Approach assigned a higher-than-requested speed; the crew accepted and the assignment did not cause the stall.',
      poolTag: 'atc',
    },
  ],
  redHerringDraw: { min: 1, max: 3 },
  parCostStub: {
    investigatorDays: 18,
    calendarDays: 55,
    evidenceSet: [
      'maint.mel_deferred_list',
      'maint.work_orders_boots',
      'wx.icing_airmet_pirep',
      'ops.dispatch_release',
      'fdr.readout',
      'cvr.transcript',
      'structures.wreckage_map',
    ],
  },
};
