/** T6 — Uncontained engine failure / fatigue (A3, A4). Fictional only. */

import type { FailureModeTemplate } from './schema';

/**
 * Typical chain (B2.4): missed inspection / misread SB revision →
 * disk/blade fatigue fracture at high power → hydraulic loss, fire →
 * controllability / rejected-takeoff overrun.
 */
export const T6_UNCONTAINED_ENGINE: FailureModeTemplate = {
  id: 'T6',
  name: 'Uncontained engine failure (fatigue)',
  summary:
    'Fan-disk fatigue missed at inspection; uncontained failure at high power with hydraulic loss and fire.',
  archetypes: ['A3', 'A4'],
  parameters: [
    {
      key: 'failureComponent',
      description: 'fan_disk | turbine_disk | blade',
      defaultValue: 'fan_disk',
    },
    {
      key: 'phaseOfFailure',
      description: 'takeoff | climb | goAround',
      defaultValue: 'takeoff',
    },
    {
      key: 'sbRevisionAmbiguous',
      description: 'Whether the governing SB revision text was ambiguous',
      defaultValue: true,
    },
  ],
  nodes: [
    {
      id: 'latent.missed_sb_inspection',
      kind: 'latentCondition',
      tier: 'contributing',
      text: 'Maintenance missed a required fan-disk inspection interval after misreading an ambiguous service-bulletin revision.',
      revealedBy: [
        { evidenceId: 'maint.sb_ad_compliance_audit', strength: 0.95 },
        { evidenceId: 'maint.work_orders_engine', strength: 0.9 },
        { evidenceId: 'maint.engine_shop_records', strength: 0.8 },
        { evidenceId: 'parties.manufacturer_sb_letter', strength: 0.7 },
      ],
    },
    {
      id: 'precondition.fatigue_crack_present',
      kind: 'precondition',
      tier: 'precondition',
      text: 'A fatigue crack was present in the fan disk and had progressed beyond the size detectable at the last performed inspection.',
      revealedBy: [
        { evidenceId: 'lab.fractography_fan_disk', strength: 0.98 },
        { evidenceId: 'powerplants.engine_teardown', strength: 0.9 },
        { evidenceId: 'maint.sb_ad_compliance_audit', strength: 0.55 },
      ],
    },
    {
      id: 'initiating.uncontained_disk_failure',
      kind: 'initiatingEvent',
      tier: 'probableCause',
      text: 'The fan disk fractured from fatigue during high-power operation, producing an uncontained engine failure.',
      revealedBy: [
        { evidenceId: 'lab.fractography_fan_disk', strength: 0.98 },
        { evidenceId: 'fdr.readout', strength: 0.9 },
        { evidenceId: 'cvr.transcript', strength: 0.85 },
        { evidenceId: 'structures.debris_field_survey', strength: 0.8 },
      ],
    },
    {
      id: 'propagation.hydraulic_fire_loss',
      kind: 'propagation',
      tier: 'contributing',
      text: 'Released fragments severed hydraulic lines and ignited a fuel-fed fire, degrading flight controls and systems.',
      revealedBy: [
        { evidenceId: 'systems.hydraulic_exam', strength: 0.9 },
        { evidenceId: 'fdr.readout', strength: 0.85 },
        { evidenceId: 'structures.fire_pattern_survey', strength: 0.8 },
        { evidenceId: 'cvr.transcript', strength: 0.7 },
      ],
    },
    {
      id: 'crewAction.rejected_takeoff',
      kind: 'crewAction',
      tier: 'contributing',
      text: 'The crew rejected the takeoff after the failure but runway remaining was insufficient for a stop without overrun.',
      revealedBy: [
        { evidenceId: 'fdr.readout', strength: 0.9 },
        { evidenceId: 'cvr.transcript', strength: 0.85 },
        { evidenceId: 'adsb.track', strength: 0.65 },
        { evidenceId: 'atc.tower_transcript', strength: 0.7 },
      ],
    },
    {
      id: 'outcome.overrun_fire',
      kind: 'outcome',
      tier: 'contributing',
      text: 'The airplane overran the runway end, collapsed the landing gear, and sustained a post-impact fuel-fed fire.',
      revealedBy: [
        { evidenceId: 'structures.wreckage_map', strength: 0.95 },
        { evidenceId: 'structures.ground_scar_survey', strength: 0.9 },
        { evidenceId: 'survival.evacuation_survey', strength: 0.75 },
        { evidenceId: 'structures.fire_pattern_survey', strength: 0.8 },
      ],
    },
  ],
  edges: [
    { from: 'latent.missed_sb_inspection', to: 'precondition.fatigue_crack_present' },
    { from: 'precondition.fatigue_crack_present', to: 'initiating.uncontained_disk_failure' },
    { from: 'initiating.uncontained_disk_failure', to: 'propagation.hydraulic_fire_loss' },
    { from: 'initiating.uncontained_disk_failure', to: 'crewAction.rejected_takeoff' },
    { from: 'propagation.hydraulic_fire_loss', to: 'outcome.overrun_fire' },
    { from: 'crewAction.rejected_takeoff', to: 'outcome.overrun_fire' },
  ],
  flightScriptHooks: [
    {
      phase: 'takeoff',
      eventId: 'event.high_power_set',
      description: 'Takeoff thrust set; N1/N2 climb toward target.',
      atSeconds: 5,
    },
    {
      phase: 'takeoff',
      eventId: 'event.disk_burst',
      description: 'Fan disk fractures; uncontained fragments exit the nacelle.',
      atSeconds: 25,
    },
    {
      phase: 'takeoff',
      eventId: 'event.hyd_fire_warning',
      description: 'Hydraulic quantity collapse and fire warnings; rejected takeoff begun.',
      atSeconds: 28,
    },
    {
      phase: 'landing',
      eventId: 'event.overrun',
      description: 'Stop margin insufficient; overrun, gear collapse, post-impact fire.',
      atSeconds: 20,
    },
  ],
  evidenceHooks: [
    {
      evidenceId: 'maint.sb_ad_compliance_audit',
      group: 'maintenanceRecords',
      title: 'AD/SB compliance audit (fan disk / engine)',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 3,
      leadTimeStub: 7,
    },
    {
      evidenceId: 'maint.work_orders_engine',
      group: 'maintenanceRecords',
      title: 'Recent engine work orders and shop visit history',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'maint.engine_shop_records',
      group: 'maintenanceRecords',
      title: 'Engine shop / NDT inspection records',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 3,
      leadTimeStub: 10,
    },
    {
      evidenceId: 'parties.manufacturer_sb_letter',
      group: 'parties',
      title: 'Manufacturer SB revision correspondence',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 2,
      leadTimeStub: 8,
    },
    {
      evidenceId: 'lab.fractography_fan_disk',
      group: 'structures',
      title: 'Materials lab fractography — fan disk',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 5,
      leadTimeStub: 30,
    },
    {
      evidenceId: 'powerplants.engine_teardown',
      group: 'powerplants',
      title: 'Engine teardown and fan-module exam',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 5,
      leadTimeStub: 25,
    },
    {
      evidenceId: 'structures.debris_field_survey',
      group: 'structures',
      title: 'Runway / off-runway debris field survey',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'systems.hydraulic_exam',
      group: 'systems',
      title: 'Hydraulic system continuity and puncture exam',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 3,
      leadTimeStub: 10,
    },
    {
      evidenceId: 'structures.fire_pattern_survey',
      group: 'structures',
      title: 'Fire-pattern and melt-directionality survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 3,
      leadTimeStub: 7,
    },
    {
      evidenceId: 'structures.wreckage_map',
      group: 'structures',
      title: 'Wreckage distribution map and PIP',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 3,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'structures.ground_scar_survey',
      group: 'structures',
      title: 'Ground-scar and overrun path survey',
      withoutRecorders: true,
      renderer: 'photo-set',
      costStub: 2,
      leadTimeStub: 4,
    },
    {
      evidenceId: 'survival.evacuation_survey',
      group: 'survivalFactors',
      title: 'Evacuation / survival-factors survey',
      withoutRecorders: true,
      renderer: 'document',
      costStub: 3,
      leadTimeStub: 8,
    },
    {
      evidenceId: 'adsb.track',
      group: 'atc',
      title: 'ADS-B track reconstruction',
      withoutRecorders: true,
      renderer: 'map',
      costStub: 1,
      leadTimeStub: 2,
    },
    {
      evidenceId: 'atc.tower_transcript',
      group: 'atc',
      title: 'Tower voice transcript',
      withoutRecorders: true,
      renderer: 'transcript',
      costStub: 2,
      leadTimeStub: 5,
    },
    {
      evidenceId: 'cvr.transcript',
      group: 'recorders',
      title: 'CVR transcript',
      withoutRecorders: false,
      renderer: 'transcript',
      costStub: 3,
      leadTimeStub: 14,
    },
    {
      evidenceId: 'fdr.readout',
      group: 'recorders',
      title: 'FDR readout (full)',
      withoutRecorders: false,
      renderer: 'trace',
      costStub: 3,
      leadTimeStub: 14,
    },
  ],
  redHerringPool: [
    {
      id: 'nonCausal.checklist_deviation_nonfactor',
      text: 'A checklist deviation on pushback was noted; it did not contribute to the engine failure or overrun.',
      poolTag: 'crew',
    },
    {
      id: 'nonCausal.gusty_crosswind',
      text: 'Gusty crosswind existed at departure; takeoff performance margins were adequate and wind was not causal.',
      poolTag: 'weather',
    },
    {
      id: 'nonCausal.unrelated_deferred_galley',
      text: 'A galley oven MEL item was open; it had no effect on propulsion, hydraulics, or evacuation.',
      poolTag: 'mel',
    },
    {
      id: 'nonCausal.prior_bird_strike_other_fleet',
      text: 'Another airplane in the fleet had a recent bird strike; that event was unrelated to this fan disk.',
      poolTag: 'history',
    },
  ],
  redHerringDraw: { min: 1, max: 3 },
  parCostStub: {
    investigatorDays: 28,
    calendarDays: 90,
    evidenceSet: [
      'maint.sb_ad_compliance_audit',
      'lab.fractography_fan_disk',
      'powerplants.engine_teardown',
      'fdr.readout',
      'cvr.transcript',
      'structures.debris_field_survey',
      'systems.hydraulic_exam',
    ],
  },
};
